#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: ceshi

env:
  BRANCHES: 22.03.2
  PREFIX_URL: https://downloads.openwrt.org/releases/22.03.2/targets

on:
  workflow_dispatch:
    inputs:
      INPUT_TARGET:
        description: "Target to build x86-64"
        required: false
        default: "x86_64/x86/64/linux-amd64/amd64"
  schedule:
    - cron: 0 0 * * *

jobs:
  Config:
    name: Generate Config
    runs-on: ubuntu-latest
    outputs:
      TARGETS: ${{ steps.find-targets.outputs.TARGETS }}

    steps:
      - name: Download Image Builder
        run: |
          wget -q $PREFIX_URL/$DEVICE_TARGET/$DEVICE_SUBTARGET/openwrt-imagebuilder-$BRANCHES-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64.tar.xz
        
      - name: Copy file
        run: |
          xz -d openwrt-imagebuilder-$BRANCHES-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64.tar.xz
          tar zxf openwrt-imagebuilder-$BRANCHES-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64.tar
          Copy 'openwrt-imagebuilder-$BRANCHES-$DEVICE_TARGET-$DEVICE_SUBTARGET.Linux-x86_64/' '${{ github.workspace }}/openwrt-kmods/kmod-packages'
        shell: powershell
