#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: ceshi

env:
  BRANCHES: 22.03.2
  PREFIX_URL: https://downloads.openwrt.org/releases/22.03.2/targets

on:
  workflow_dispatch:
    inputs:
      INPUT_TARGET:
        description: "Target to build x86-64"
        required: false
        default: "x86_64/x86/64/linux-amd64/amd64"
  schedule:
    - cron: 0 0 * * *

jobs:
  Config:
    name: Generate Config
    runs-on: ubuntu-latest

    steps:
      - name: Download Image Builder
        run: |
          wget -q $PREFIX_URL/x86/64/openwrt-imagebuilder-22.03.2-x86-64.Linux-x86_64.tar.xz
        
      - name: Copy file
        run: |
          tar -xJf openwrt-imagebuilder-22.03.2-x86-64.Linux-x86_64.tar.xz
      - name: Upload
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE/openwrt-imagebuilder-22.03.2-x86-64.Linux-x86_64
          git add .
          git commit -am "update $(date +%Y-%m-%d" "%H:%M:%S)"
          git push --quiet "https://${{ secrets.ACCESS_TOKEN }}@github.com/hululuxi/x86-kmods-compile.git"
